# File: .github/workflows/azure-login.yml
name: Azure Login

on: [push]

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify login
        run: az account show
